### ISSUE TITLE
Importer can't read module doc strings in CI/QA environment

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy-dev#107]
The importer seems to crash when I try to upload my test collection to ci.cloud.redhat.com. It looks like the importer doesn't have permissions to read modules.

```
===== LOADING MODULE: real_facts ===== 
Getting doc strings via ansible-doc 
Error running ansible-doc: b'Unhandled error:
 Traceback (most recent call last):
 File "/venv/lib64/python3.6/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
 os.makedirs(b_rpath, mode)
 File "/usr/lib64/python3.6/os.py", line 210, in makedirs
 makedirs(head, mode, exist_ok)
 File "/usr/lib64/python3.6/os.py", line 220, in makedirs
 mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b\'/.ansible\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 550, in update_config_data
 value, origin = self.get_config_value_and_origin(config, configfile)
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 494, in get_config_value_and_origin
 value = ensure_type(value, defs[config].get(\'type\'), origin=origin)
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 121, in ensure_type
 makedirs_safe(value, 0o700)
 File "/venv/lib64/python3.6/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
 raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b\'/.ansible\'


Traceback (most recent call last):
 File "/venv/lib64/python3.6/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
 os.makedirs(b_rpath, mode)
 File "/usr/lib64/python3.6/os.py", line 210, in makedirs
 makedirs(head, mode, exist_ok)
 File "/usr/lib64/python3.6/os.py", line 220, in makedirs
 mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b\'/.ansible\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 550, in update_config_data
 value, origin = self.get_config_value_and_origin(config, configfile)
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 494, in get_config_value_and_origin
 value = ensure_type(value, defs[config].get(\'type\'), origin=origin)
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 121, in ensure_type
 makedirs_safe(value, 0o700)
 File "/venv/lib64/python3.6/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
 raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b\'/.ansible\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/venv/bin/ansible-doc", line 62, in <module>
 import ansible.constants as C
 File "/venv/lib64/python3.6/site-packages/ansible/constants.py", line 174, in <module>
 config = ConfigManager()
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 290, in __init__
 self.update_config_data()
 File "/venv/lib64/python3.6/site-packages/ansible/config/manager.py", line 562, in update_config_data
 raise AnsibleError("Invalid settings supplied for %s: %s\
" % (config, to_native(e)), orig_exc=e)
ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b\'/.ansible\'

' 
```

**Comment by awcrosby** [comment]
A potential fix https://github.com/ansible/galaxy-dev/pull/110, would need to be tested in the ci environment
