### ISSUE TITLE
Permission issue on calling ansible-test from hub-importer-plugin

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy-dev#141]
Environment: https://ci.cloud.redhat.com/beta/ansible/automation-hub/

When importing a collection in the CI environment (which now includes `hub-importer-plugin`), at the end of the import process `ansible-test sanity` is run. A permission error occurred and ansible-test did not complete:

```
Traceback (most recent call last): 
File "/venv/bin/ansible-test", line 28, in <module> 
main() 
File "/venv/bin/ansible-test", line 24, in main 
cli_main() 
File "/venv/lib64/python3.6/site-packages/ansible_test/_internal/cli.py", line 128, in main 
args.func(config) 
File "/venv/lib64/python3.6/site-packages/ansible_test/_internal/sanity/__init__.py", line 92, in command_sanity 
install_command_requirements(args) 
File "/venv/lib64/python3.6/site-packages/ansible_test/_internal/executor.py", line 197, in install_command_requirements 
generate_egg_info(args) 
File "/venv/lib64/python3.6/site-packages/ansible_test/_internal/executor.py", line 316, in generate_egg_info 
write_text_file(pkg_info_path, pkg_info.lstrip(), create_directories=True) 
File "/venv/lib64/python3.6/site-packages/ansible_test/_internal/util_common.py", line 163, in write_text_file 
make_dirs(os.path.dirname(path)) 
File "/venv/lib64/python3.6/site-packages/ansible_test/_internal/util.py", line 529, in make_dirs 
os.makedirs(to_bytes(path)) 
File "/usr/lib64/python3.6/os.py", line 220, in makedirs 
mkdir(name, mode) 
PermissionError: [Errno 13] Permission denied: b'/venv/lib64/python3.6/site-packages/ansible.egg-info' 
```

**Comment by awcrosby** [comment]
Confirmed on a local `galaxy-dev` env, that `/venv/lib64/python3.6/site-packages/ansible.egg-info/PKG_INFO` is created without permissions error and `ansible-test sanity` proceeds.

2 possible options to resolve:
1. Add write access to `/venv` in deployed environments
2. Use the `ansible-test sanity` managed virtual env (current part of https://github.com/ansible/hub-importer-plugin/pull/3), which creates a separate venv inside `/tmp`... write access would be needed there
