### ISSUE TITLE
API: Can't upload collections

### ISSUE THREAD

**Issue by romanblanco** [ansible/galaxy-dev#163]
I'm getting errors while uploading a collection on my local CI:

```
galaxy-api_1             |   File "/code/galaxy-api/galaxy_api/api/v3/viewsets.py", line 183, in post
galaxy-api_1             |     path='ansible/collections/',
galaxy-api_1             | KeyError: 'prefix'
```

looks like the string needs the removed `prefix`: https://github.com/ansible/galaxy-api/commit/f78082d0#diff-4197903b42a52e1f7f468e56e20a25e8L128

I've tried:

```
+
+        # url = '{host}/{prefix}/{path}'.format(
+        #     host=api.configuration.host,
+        #     prefix=settings.API_PATH_PREFIX,
+        #     path='ansible/collections/',
+        # )
+        #
+        # pulp-api_1               | Not Found: /api/automation-hub/ansible/collections/
```
```
+        # url = '{host}/{path}'.format(
+        #     host=api.configuration.host,
+        #     path='ansible/collections/',
+        # )
+        #
+        # galaxy-api_1             | Internal Server Error: /api/automation-hub/v3/artifacts/collections/
+        # galaxy-api_1             | Traceback (most recent call last):
+        # galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
+        # galaxy-api_1             |     return self.cursor.execute(sql, params)
+        # galaxy-api_1             | psycopg2.errors.NotNullViolation: null value in column "task_id" violates not-null constraint
+        # galaxy-api_1             | DETAIL:  Failing row contains (null, null, collection_demo, 1.0.10, 5).
```
```
+        # url = '{host}/{prefix}{path}'.format(
+        #     host=api.configuration.host,
+        #     prefix=settings.API_PATH_PREFIX,
+        #     path='ansible/collections/',
+        # )
+        #
+        # galaxy-api_1             | Failed to publish artifact rblanco-collection_demo-1.0.13.tar.gz (namespace=rblanco, sha256=None) to pulp at url=http://pulp-api:8000/api/automation-huba
nsible/coll
+        # ections/
+        # galaxy-api_1             | Traceback (most recent call last):
+        # galaxy-api_1             |   File "/code/galaxy-api/galaxy_api/api/v3/viewsets.py", line 245, in post
+        # galaxy-api_1             |     post_params=post_params,
+        # galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/galaxy_pulp/api_client.py", line 386, in request
+        # galaxy-api_1             |     body=body)
+        # galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/galaxy_pulp/rest.py", line 276, in POST
+        # galaxy-api_1             |     body=body)
+        # galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/galaxy_pulp/rest.py", line 229, in request
+        # galaxy-api_1             |     raise ApiException(http_resp=r)
+        # galaxy-api_1             | galaxy_pulp.exceptions.ApiException: (404)
+        # galaxy-api_1             | Reason: Not Found
```

**Comment by alikins** [comment]
@romanblanco https://github.com/ansible/galaxy-api/pull/118 should fix this.
