### ISSUE TITLE
Upload doesn't check if namespace exists

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy-dev#85]
The upload API doesn't check to see if namespaces exist. When collections are added to pulp that don't have corresponding namespaces in galaxy API, the entire collections endpoint crashes with this error

```

Traceback:

File "/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/venv/lib64/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/venv/lib64/python3.6/site-packages/rest_framework/viewsets.py" in view
  114.             return self.dispatch(request, *args, **kwargs)

File "/venv/lib64/python3.6/site-packages/rest_framework/views.py" in dispatch
  497.             response = self.handle_exception(exc)

File "/venv/lib64/python3.6/site-packages/rest_framework/views.py" in handle_exception
  457.             self.raise_uncaught_exception(exc)

File "/venv/lib64/python3.6/site-packages/rest_framework/views.py" in raise_uncaught_exception
  468.         raise exc

File "/venv/lib64/python3.6/site-packages/rest_framework/views.py" in dispatch
  494.             response = handler(request, *args, **kwargs)

File "/code/galaxy-api/galaxy_api/api/ui/viewsets/collection.py" in list
  34.             response.results, many=True, context={'namespace_dict': namespaces}

File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py" in data
  757.         ret = super().data

File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py" in data
  261.                 self._data = self.to_representation(self.instance)

File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py" in to_representation
  675.             self.child.to_representation(item) for item in iterable

File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py" in <listcomp>
  675.             self.child.to_representation(item) for item in iterable

File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py" in to_representation
  526.                 ret[field.field_name] = field.to_representation(attribute)

File "/venv/lib64/python3.6/site-packages/rest_framework/fields.py" in to_representation
  1873.         return method(value)

File "/code/galaxy-api/galaxy_api/api/ui/serializers/collection.py" in get_namespace
  82.             namespace = self.context['namespace_dict'][namespace]

Exception Type: KeyError at /api/automation-hub/v3/_ui/collections/
Exception Value: 'newswangerd_galaxy_test'
```

**Comment by alikins** [comment]
I can reproduce this. Uploaded a collection built for 'unknownns' namespace and
then hit "http://127.0.0.1:5001/api/automation-hub/v3/_ui/collections/"

```
alaxy-api_1             | DEBUG 2019-09-05 19:57:35,417 django.db.backends utils 42 140245869766400 (0.001) SELECT "galaxy_api_namespace"."id", "galaxy_api_namespace"."name", "galaxy_api_namespace"."company", "galaxy_api_namespace"."email", "galaxy_api_namespace"."avatar_url", "galaxy_api_namespace"."description", "galaxy_api_namespace"."resources" FROM "galaxy_api_namespace" WHERE "galaxy_api_namespace"."name" IN ('alikins', 'myns', 'unknownns'); args=('alikins', 'myns', 'unknownns')
galaxy-api_1             | DEBUG 2019-09-05 19:57:35,420 django.db.backends utils 42 140245869766400 (0.001) SELECT "galaxy_api_namespacelink"."id", "galaxy_api_namespacelink"."name", "galaxy_api_namespacelink"."url", "galaxy_api_namespacelink"."namespace_id" FROM "galaxy_api_namespacelink" WHERE "galaxy_api_namespacelink"."namespace_id" = 2; args=(2,)
galaxy-api_1             | DEBUG 2019-09-05 19:57:35,422 django.db.backends utils 42 140245869766400 (0.000) SELECT "galaxy_api_namespacelink"."id", "galaxy_api_namespacelink"."name", "galaxy_api_namespacelink"."url", "galaxy_api_namespacelink"."namespace_id" FROM "galaxy_api_namespacelink" WHERE "galaxy_api_namespacelink"."namespace_id" = 2; args=(2,)
galaxy-api_1             | DEBUG 2019-09-05 19:57:35,424 django.db.backends utils 42 140245869766400 (0.000) SELECT "galaxy_api_namespacelink"."id", "galaxy_api_namespacelink"."name", "galaxy_api_namespacelink"."url", "galaxy_api_namespacelink"."namespace_id" FROM "galaxy_api_namespacelink" WHERE "galaxy_api_namespacelink"."namespace_id" = 1; args=(1,)
galaxy-api_1             | Internal Server Error: /api/automation-hub/v3/_ui/collections/
galaxy-api_1             | Traceback (most recent call last):
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
galaxy-api_1             |     response = get_response(request)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
galaxy-api_1             |     response = self.process_exception_by_middleware(e, request)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
galaxy-api_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
galaxy-api_1             |     return view_func(*args, **kwargs)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
galaxy-api_1             |     return self.dispatch(request, *args, **kwargs)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
galaxy-api_1             |     response = self.handle_exception(exc)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 457, in handle_exception
galaxy-api_1             |     self.raise_uncaught_exception(exc)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
galaxy-api_1             |     raise exc
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
galaxy-api_1             |     response = handler(request, *args, **kwargs)
galaxy-api_1             |   File "/code/galaxy-api/galaxy_api/api/ui/viewsets/collection.py", line 34, in list
galaxy-api_1             |     response.results, many=True, context={'namespaces': namespaces}
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py", line 757, in data
galaxy-api_1             |     ret = super().data
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py", line 261, in data
galaxy-api_1             |     self._data = self.to_representation(self.instance)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py", line 675, in to_representation
galaxy-api_1             |     self.child.to_representation(item) for item in iterable
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py", line 675, in <listcomp>
galaxy-api_1             |     self.child.to_representation(item) for item in iterable
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/serializers.py", line 526, in to_representation
galaxy-api_1             |     ret[field.field_name] = field.to_representation(attribute)
galaxy-api_1             |   File "/venv/lib64/python3.6/site-packages/rest_framework/fields.py", line 1873, in to_representation
galaxy-api_1             |     return method(value)
galaxy-api_1             |   File "/code/galaxy-api/galaxy_api/api/ui/serializers/collection.py", line 78, in get_namespace
galaxy-api_1             |     namespace = self._get_namespace(obj)
galaxy-api_1             |   File "/code/galaxy-api/galaxy_api/api/ui/serializers/collection.py", line 85, in _get_namespace
galaxy-api_1             |     return self.context['namespaces'][name]
galaxy-api_1             | KeyError: 'unknownns'
galaxy-api_1             | ERROR 2019-09-05 19:57:35,464 django.server basehttp 42 140245869766400 "GET /api/automation-hub/v3/_ui/collections/ HTTP/1.1" 500 19541
```

**Comment by alikins** [comment]
Seems like it should be okay for pulp to have collections that don't have namespaces known to galaxy-api. So galaxy-api probably needs to be able to either filter these out or ignore them. Since collections could be uploaded to pulp without ever involving galaxy-api.

Though it also makes sense for the galaxy upload api to throw errors in these cases. Will likely need similar namespace checks as the imports for community galaxy. If nothing else, just verifying the namespace in the uploaded filename is a namespace known to galaxy-api. And presumably that the uploading user is a tenant associated with that namespace (I think some of @cutwaters permission chases may be related to this?)

**Comment by alikins** [comment]
reopening this, I think https://github.com/ansible/galaxy-api/commit/2f0c869307950710611f3ccecc8d371c6ea5dd68 mistakenly referenced this issue (#85)
instead of #87
