### ISSUE TITLE
API diff between v3 and v3 for get collection that breaks ansible-galaxy (GET /collections/{namespace}/{name}/versions/{version})

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy-dev#99]
The 'v3' result for `GET /collections/{namespace}/{name}/versions/{version}` uses a different structure for the the 'namespace' field and this breaks current devel/2.9 ansible-galaxy 'install' against v3 or automation hub 

For v2, the 'namespace' value for is a dict like:
GET https://galaxy-dev.ansible.com/api/v2/collections/alikins/collection_ntp/versions/0.1.182/

``` json
    "namespace": {
        "href": "https://galaxy-dev.ansible.com/api/v1/namespaces/2271/",
        "id": 2271,
        "name": "alikins"
    },
```

But for v3, the 'namespace' value is a single string:
GET http://127.0.0.1:5001/api/automation-hub/v3/collections/alikins/collection_ntp/versions/0.1.182/

``` json
    "namespace": "alikins",
```

When attempting to install 'alikins.collection_ntp' from a v3 server, ansible-galaxy fails with:

```
(ansible-py3) [newswoop:F29:ansible (galaxy_api_introspection %)]$ ANSIBLE_DEBUG=1 ANSIBLE_CONFIG=ansible-ah.cfg ansible-galaxy collection install -s local_hub -vvv myns.collection_ntp -p /tmp/collections/
 24664 1568042148.11679: starting run
ansible-galaxy 2.10.0.dev0
  config file = /home/adrian/src/ansible/ansible-ah.cfg
  configured module search path = ['/home/adrian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible-galaxy
  python version = 3.6.9 (default, Jul  3 2019, 17:57:57) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
Using /home/adrian/src/ansible/ansible-ah.cfg as config file
 24664 1568042148.33662: Validate TLS certificates for http://localhost:5001/api/automation-hub/: True
 24664 1568042148.34686: Validate TLS certificates for http://localhost:8000: True
 24664 1568042148.35449: Validate TLS certificates for https://galaxy.ansible.com/api/: True
 24664 1568042148.36646: Validate TLS certificates for https://galaxy-dev.ansible.com/api/: True
 24664 1568042148.37442: Validate TLS certificates for https://galaxy-qa.ansible.com/api/: True
 [WARNING]: The specified collections path '/tmp/collections' is not part of the configured Ansible collections paths '/home/adrian/.ansible/collections:/usr/share/ansible/collections'. The installed collection
won't be picked up in an Ansible run.

Process install dependency map
 24664 1568042148.37516: Starting display_progress display thread
Opened /home/adrian/.ansible/galaxy_token
Processing requirement collection 'myns.collection_ntp'
Collection 'myns.collection_ntp' obtained from server local_hub http://localhost:5001/api/automation-hub/
 24664 1568042148.47785: Received end signal for display_progress display thread
Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/galaxy.py", line 348, in run
    context.CLIARGS['func']()
  File "/home/adrian/src/ansible/lib/ansible/cli/galaxy.py", line 804, in execute_install
    no_deps, force, force_deps)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/collection.py", line 414, in install_collections
    validate_certs, force, force_deps, no_deps)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/collection.py", line 766, in _build_dependency_map
    if parent_info.dependencies:
  File "/home/adrian/src/ansible/lib/ansible/galaxy/collection.py", line 108, in dependencies
    self._get_metadata()
  File "/home/adrian/src/ansible/lib/ansible/galaxy/collection.py", line 189, in _get_metadata
    self._metadata = self.api.get_collection_version_metadata(self.namespace, self.name, self.latest_version)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/api.py", line 74, in wrapped
    return method(self, *args, **kwargs)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/api.py", line 514, in get_collection_version_metadata
    return CollectionVersionMetadata(data['namespace']['name'], data['collection']['name'], data['version'],
TypeError: string indices must be integers
```

**Comment by alikins** [comment]
Full result output for the v2 vs v3 cases. Note the difference in 'namespace' structure.

v2 https://galaxy-dev.ansible.com/api/v2/collections/alikins/collection_ntp/versions/0.1.182/:
``` json
{
    "artifact": {
        "filename": "alikins-collection_ntp-0.1.182.tar.gz",
        "sha256": "ea7beadcfac82e82af7f89e4d07898d00075ca5459ab92cd64b88a4e72cedd67",
        "size": 8204
    },
    "collection": {
        "href": "https://galaxy-dev.ansible.com/api/v2/collections/alikins/collection_ntp/",
        "id": 25,
        "name": "collection_ntp"
    },
    "download_url": "https://galaxy-dev.ansible.com/download/alikins-collection_ntp-0.1.182.tar.gz",
    "hidden": false,
    "href": "https://galaxy-dev.ansible.com/api/v2/collections/alikins/collection_ntp/versions/0.1.182/",
    "id": 20079,
    "metadata": {
        "authors": [
            "geerlingguy"
        ],
        "dependencies": {},
        "description": "NTP installation and configuration for Linux.",
        "documentation": null,
        "homepage": null,
        "issues": null,
        "license": [
            "MIT"
        ],
        "license_file": null,
        "name": "collection_ntp",
        "namespace": "alikins",
        "readme": "README.md",
        "repository": null,
        "tags": [
            "system",
            "ntp",
            "date",
            "time",
            "timezone"
        ],
        "version": "0.1.182"
    },
    "namespace": {
        "href": "https://galaxy-dev.ansible.com/api/v1/namespaces/2271/",
        "id": 2271,
        "name": "alikins"
    },
    "version": "0.1.182"
}
```

v3 http://127.0.0.1:5001/api/automation-hub/v3/collections/alikins/collection_ntp/versions/0.1.182/

``` json
{
    "artifact": {
        "filename": "alikins.collection_ntp.0.1.182",
        "sha256": "ea7beadcfac82e82af7f89e4d07898d00075ca5459ab92cd64b88a4e72cedd67",
        "size": 8204
    },
    "collection": {
        "href": "/api/automation-hub/v3/collections/alikins/collection_ntp/",
        "id": "3c2ad808-059d-41ac-b7a5-fe622f5edcdb",
        "name": "collection_ntp"
    },
    "created_at": "2019-09-09T15:19:19.704602Z",
    "download_url": "/api/v3/artifacts/collections/alikins.collection_ntp.0.1.182",
    "href": "/api/automation-hub/v3/collections/alikins/collection_ntp/versions/0.1.182/",
    "is_certified": false,
    "metadata": {
        "authors": [
            "geerlingguy"
        ],
        "contents": [],
        "dependencies": {},
        "description": "NTP installation and configuration for Linux.",
        "documentation": "",
        "homepage": "",
        "issues": "",
        "license": [
            "MIT"
        ],
        "repository": "",
        "tags": [
            "system",
            "ntp",
            "date",
            "time",
            "timezone"
        ]
    },
    "name": "collection_ntp",
    "namespace": "alikins",
    "updated_at": "2019-09-09T15:19:19.704628Z",
    "version": "0.1.182"
}
```

**Comment by alikins** [comment]
As far as I can tell, ansible-galaxy doesn't need the full dict from the v3 output, it just needs the 'name' field. So v3 namespace format could be:

``` json
...
  "namespace": {
      "name": "alikins"
  },
...
```

(Since namespace href and id aren't necessarily known by pulp)

**Comment by alikins** [comment]
pinging @bmbouter

**Comment by alikins** [comment]
I've started updating galaxy_api.api.v3.viewsets.CollectionVersionViewSet.retrieve() for this.

Some tweaks galaxy-api needs to the apply to the output from pulp for the response to match  https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ansible/galaxy-api/master/openapi/openapi.yaml#/Collections/getCollectionVersions:

- [ ] Make 'namespace' value a dict
  - [ ] Make `namespace['name']` the namespace name
  - [ ] Optional? Lookup namespace id and galaxy-api href from galaxy api and add to 'namespace' dict
- [ ] Augment the `metadata` dict in galaxy_api response to include:
   - [ ] namespace
   - [ ] name
   - [ ] version
   - [ ] readme
- [ ] (optional?) - remove the 'contents' from the 'metadata' dict in the pulp response
- [ ] Transform rel to full urls
  - [ ] Transform the 'download_url' to a full url. ie, "https://galaxy-dev.ansible.com/download/alikins-collection_ntp-0.1.182.tar.gz"  instead of the relative url in pulp response like "/api/v3/artifacts/collections/myns.collection_ntp.0.1.182"
  - [ ]  various other href's and links
    - [ ] collection
    - [ ] namespace
    - [ ] collection version href
